### ISSUE TITLE
Builder.add with VarArgs

### ISSUE THREAD

**Issue by tmtron** [immutables/immutables-vavr#13]
Can we change the builder.add method to accept VarArgs?

So instead of 
    
    ImmutableExampleSetType.Builder b = ImmutableExampleSetType.builder()
    b.addIntegers(Integer.valueOf(0));
    b.addIntegers(Integer.valueOf(1));
    b.addIntegers(Integer.valueOf(2));

we can additionally use: 

    ImmutableExampleSetType.builder();
    b.addIntegers(Integer.valueOf(0), Integer.valueOf(1), Integer.valueOf(2));

e.g. In a branch of my fork, I've implemented it for `Set`: see this [changeset](https://github.com/tmtron/immutables-vavr/commit/7b5001358115ad4405ce674146f5c894889f76c0)

BTW: Is there a reason why you use explicit boxing of integer types in your tests?

**Comment by io7m** [comment]
> Can we change the builder.add method to accept VarArgs?

I'd prefer to add a method rather than change the existing one, to ensure compatibility with existing clients.

> BTW: Is there a reason why you use explicit boxing of integer types in your tests?

It's habit, really. I work with a lot of code that has soft-realtime requirements ([r2](http://github.com/io7m/r2), etc) and so my IDE is configured to ensure that boxing is explicit. Makes it clear when code might conceivably create garbage.
